#!/bin/bash

CY_MISC_SH_FILE="cy-misc.inc"
if ! . $(dirname $0)/$CY_MISC_SH_FILE ; then
        echo "$0: fatal error! Cannot source $CY_MISC_SH_FILE"
        exit 1
fi

#
# Usage
#

function usage ( ) {
	echo "usage:" >&2
	echo "       $NAME find <name> [<name> ...]" >&2
	echo "       $NAME recipe <name> [<name> ...]" >&2
	echo "       $NAME depends <name> [<name> ...]" >&2
	echo "       $NAME inspect|get-info <file.ipk>" >&2
	exit 1
}

#
# Main
#

[ $# -lt 1 ] && usage
cmd=$1
name=$2

set -e

case $cmd in
find)
	info "searching in $BUILDDIR..."
	cd $BUILDDIR
	shift
	for n in $@ ; do
		find tmp/deploy/ipk/ -name "${n}*"
	done
	exit 0
	;;

recipe)
	shift
	for n in $@ ; do
		echo -n "package $n is provided by: "
		oe-pkgdata-util lookup-recipe $n
	done
	exit 0
	;;

depends)
	shift
	for n in $@ ; do
		if ! oe-pkgdata-util list-pkgs $n 2>/dev/null 1>&2 ; then
			warn "cannot find package $n!"
			continue
		fi
		echo -n "package $n depends on: "
		oe-pkgdata-util read-value RDEPENDS $n
	done
	exit 0
	;;

inspect)
	dpkg -c $BUILDDIR/$name
	exit 0
	;;

get-info)
	dpkg -f $BUILDDIR/$name
	exit 0
	;;

*)
	fatal "invalid subcommand \"$cmd\""
esac

# Can't happen!
exit 1
