#!/bin/bash

CY_MISC_SH_FILE="cy-misc.inc"
if ! . $(dirname $0)/$CY_MISC_SH_FILE ; then
        echo "$0: fatal error! Cannot source $CY_MISC_SH_FILE"
        exit 1
fi

info "hello world!"
info "CY_METADIR=$CY_METADIR"

exit 0
